# Generated by Django 3.1 on 2020-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=180)),
                ('reason', models.TextField(blank=True)),
                ('appointment_made_time', models.DateTimeField(auto_now=True)),
                ('appointment_time', models.DateTimeField(null=True)),
                ('status', models.CharField(default='P', max_length=20)),
            ],
            options={
                'ordering': ['-appointment_made_time'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('specialization', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted_name', models.CharField(max_length=180)),
                ('trusted_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
