# Generated by Django 3.1 on 2020-08-10 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted_name', models.CharField(max_length=180)),
                ('trusted_phone', models.CharField(max_length=15, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
