# Generated by Django 3.1 on 2020-08-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0003_trustedcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
