# Generated by Django 3.1 on 2020-08-11 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0009_auto_20200811_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(blank=True, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
