# Generated by Django 3.1 on 2020-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0011_auto_20200812_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustedcontact',
            name='trusted_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='trustedcontact',
            unique_together={('user', 'trusted_phone')},
        ),
    ]
