# Generated by Django 3.1 on 2020-08-13 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0013_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='OTP',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 19, 40, 8, 519078)),
        ),
    ]
