# Generated by Django 3.1 on 2020-08-13 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0014_auto_20200813_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-expiry']},
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 20, 1, 53, 965250)),
        ),
    ]
