# Generated by Django 3.1 on 2020-08-13 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0015_auto_20200813_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 17, 52, 56, 347111, tzinfo=utc)),
        ),
    ]
