# Generated by Django 3.1 on 2020-08-13 18:12

from django.db import migrations, models
import halemate.models


class Migration(migrations.Migration):

    dependencies = [
        ('halemate', '0016_auto_20200813_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry',
            field=models.DateTimeField(default=halemate.models.get_expiry),
        ),
    ]
